/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  identity: {
    Login: () => import('#app/identity/controllers/login_controller'),
    Register: () => import('#app/identity/controllers/register_controller'),
    Session: () => import('#app/identity/controllers/session_controller'),
  },
}
